# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions" # Output for Netlify serverless functions

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
